trigger:
  - master

schedules:
  - cron: 0 * * * *
    displayName: hourly schedule
    branches:
      include:
      - master
  
pool:
  vmImage: 'ubuntu-latest'


steps:      
  - task: PowerShell@2
    displayName: python/shell trigger scheduling
    inputs:
      filePath: 'Start-Pipeline.ps1'
    env:
      SYSTEM_ACCESSTOKEN: $(pat)
      STORAGEACCOUNTNAME: $(storageaccount)
      STORAGEACCOUNTKEY: $(storageaccountkey)

